version: '3'
services:
  database:
    image: mysql
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./:/docker-entrypoint-initdb.d

    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  mongodb-database:
    image: mongo
    ports:
      - 27017:27017